### ISSUE TITLE
Add ability for owners to disable their own interactions

### ISSUE THREAD

**Issue by AutonomousCat** [pop4959/Bolt#100]
**Idea:** `/bolt weld`

**Description:**
Upon command usage, the player must right click on their own lockable (or already locked) item. This then disables all interaction types (or as configured, as a protection type).

The idea stemmed from my question in the Discord server about protecting dragon eggs, for the purposes of keeping it from teleporting. Realizing it wouldn't stop the owner from accidentally clicking on it, I thought of all the instances where someone might want to stop interactions and thought "how about /bolt weld?"

For example, accidentally clicking on:
- decorative doors/trapdoors
- redstone repeaters set to a specific delay
- items in frames you don't want to spin
- bells you don't want to ring

**Comment by pop4959** [comment]
I'm not sure about the command because it seems highly specific, but this might lead back to wanting some sort of flags system or negative permissions for protections. Or a configuration for specific mechanics and interactions with protections (as there get to be a bunch of edge cases here potentially, I just don't want to clutter the main config with it).

**Comment by pop4959** [comment]
The more I've thought about this the more I realize this doesn't really work in a nice enough way to where I'm comfortable with it as a feature currently. Denying interaction for the owner means that they are also no longer able to interact with their own protections for other reasons, without there being an entirely separate system for this, but this is not something I really want to get into. The easy solution here is to "just not accidentally click/interact with your own stuff", and I'm pretty sure that's what 99% of other protection plugins expect here.

That said, for now I'm going to close this issue. That isn't to say that this is per se "rejected", but the idea in its current form is not something that I would like to pursue for the reasons mentioned above. It's possible in the future that something else will take its place and offer some similar level of functionality. If you have any ideas feel free to discuss on our Discord server.
