### ISSUE TITLE
cant break blocks

### ISSUE THREAD

**Issue by maIwina** [pop4959/Bolt#105]
after using /bolt:bolt info you cant break blocks and instead it just says that block is locked or isnt locked even if its my own block 
mc version 1.20 fabric

**Comment by pop4959** [comment]
I am not able to reproduce this issue. Would you be able to provide more information or demonstrate it for me?

Also just checking, this isn't running on a Fabric server, correct? Bolt currently does not officially support Fabric, so if you are doing something to force it to run there you may experience odd behavior, and unfortunately it is unsupported.

**Comment by maIwina** [comment]
yeah that could explain that bolt doesnt support fabric
