### ISSUE TITLE
Double door towny bug

### ISSUE THREAD

**Issue by Lorias-Jak** [pop4959/Bolt#139]
Message from dc:

Hey There! The shown Account stands in a Town (from Towny) and is not a resident. Outsider-Switch is turned off, so he should not be allowed to open doors. 

Infront of the player is a double door with a public lock. As you can see, if the account interacts with one side, the action gets cancelled, but the other half opens. Normally none of the doors should open, because its an outsider and no interaction with doors is allowed by towny

https://github.com/pop4959/Bolt/assets/62625225/d885aefa-6567-4136-a908-61239199adef

**Comment by pop4959** [comment]
Fixed in 179157b7afa14fcf372a81362df28c578a980e17

**Comment by Lorias-Jak** [comment]
Thank you for the quick fix!
