### ISSUE TITLE
ItemFrameMatcher error on Folia

### ISSUE THREAD

**Issue by tksskt** [pop4959/Bolt#140]
I am using bolt on the folia server, but an error related to bolt is displayed.
Is there any solution?
Java version: openjdk 21.0.2 2024-01-16
Server version: folia-1.20.4
bolt version:1.0.579
error log : https://bytebin.lucko.me/o43LvGapEo

We currently do not know how to reproduce the issue, but we have confirmed that the error occurs when players are participating.

**Comment by pop4959** [comment]
I was not able to reproduce this issue, and unfortunately there are also no plans to backport any fixes for 1.20.4.

If this is still an issue with Folia on 1.21.1, please open a new issue and I will take a fresh look. Thanks!
