### ISSUE TITLE
Door auto-close without permission

### ISSUE THREAD

**Issue by Lorias-Jak** [pop4959/Bolt#141]
## Issue
If i use public or private locked doors they're automatically closing. There is no autoclose configured for the door. It's not important if i locked the door myself or a other player locked it. It closes every time. 
If my users uses the door, it stays open as they dont have that much permissions or op. It does not close automatically

## Tested on 
* 1.20.4-paper-496
* Java 17
* Clean install, only Bolt as plugin

## Conditions
* op on the player
* a private or public locked door

## Attachments
* Link to the dc-conversation: https://discord.com/channels/390942438061113344/479919881702342676/1245448267890950145
* Video of the Issue: https://github.com/pop4959/Bolt/assets/62625225/79712915-fbb1-45e5-9c5f-14fe277fa133
* [config.zip](https://github.com/pop4959/Bolt/files/15489711/config.zip)

**Comment by pop4959** [comment]
Borderline not a bug, basically looks like it was just permission defaults not being set for the `bolt.permission.<permission>` overrides. Latest build should fix provided you don't have anything silly like `*` permissions set on your account.
