### ISSUE TITLE
[Feature Request] Multiple protection types on one block

### ISSUE THREAD

**Issue by Dezaku** [pop4959/Bolt#143]
It would be useful to be able to have a block with multiple protection types, so e.g you could have a chest which defaults to two protection types: the default one and one named redstone that restricts redstone. Now if someone wants to only allow redstone they can do e.g /unlock redstone and now the block is still protected with the default one but not anymore with the redstone one. Adding a "disallow" option instead of just "allow" might also be useful for that

**Comment by pop4959** [comment]
A protection can only have one protection type. There are no plans on changing this, however I do already have plans to extend the permission system. For now, in your example, a private and redstone protection type separately are a good solution though for what you are trying to achieve.
