### ISSUE TITLE
/bolt password always says password accepted

### ISSUE THREAD

**Issue by Dezaku** [pop4959/Bolt#145]
No matter if the password even exist for any block in the world, whatever password you type in with `/bolt password {password}` it always says "password accepted". I think it would be good for it to say that that password doesn't exist instead

**Comment by pop4959** [comment]
This is intentional, it would be a security issue if players could spam random passwords and be told if one is valid.

All passwords are accepted, and if they are valid, the player can use them. However, maybe the wording here could be improved.

**Comment by Dezaku** [comment]
Yeah I of course thought of that too but the wording could definitely be improved. Don't have something better in mind myself tho
