### ISSUE TITLE
Trust only works for the default access type

### ISSUE THREAD

**Issue by Kaassss** [pop4959/Bolt#147]
Bolt version 1.1.14
Paper server 1.20.6 [No other plugins]

When using, for example: `/bolt trust add player <player_name> admin` or any (custom) non-default access types, the player only gets added to the normal [default] access type.

Few things I did whilst testing:
- I made sure that I had set the admin access type to not require permission, but also tested with the permission and setting the access type to require permission.
- I also tried switching the default type to be admin, afterwards any player added to the normal access type with `/bolt trust add player <player_name> normal` was added to the admin access type.
- I only tested with `<source-type> = player` by the way. With both online and offline players.
- I changed one line in the `en.properties` to check what access type a player had in my access list:
  - `access_list_entry_default= * <source_identifier> (<source_type>: <access_type>)`
- I also confirmed that it was not just a visual bug in the access list, the player that I used in the command, was not able to edit the interaction.
- Adding a player to an individual protection through bolt modify did seem to work for all access types correctly.

**Comment by pop4959** [comment]
This was a bug awhile ago, but it should be fixed in a0d85f5dd75cab3d3e63e7b5d33091893aa2a304 already. Can you try downloading [the latest dev build](https://ci.codemc.io/view/Author/job/pop4959/job/Bolt/) and confirm? There should be a release soon to cover 1.21 changes such as new blocks and adventure update which will include these fixes.

**Comment by Kaassss** [comment]
Ah yes, that one works great! Thanks for the response.
(Not very familiar with Github, so was not aware that all changes were listed and dev builds were available, oops.)

Looking forward to the next release, good luck!

**Comment by pop4959** [comment]
No worries! Sorry for any confusion. To be honest, this fix is important enough that I should have probably released something sooner, but I promise there will be one soon enough. On the other hand, I'm surprised we haven't gotten more reports about this bug (which started after the big modify/trust refactor).
