### ISSUE TITLE
[Bug] Locked hoppers or hopper carts belonging to player "a" can steal the items of locked containers belonging to player "b"

### ISSUE THREAD

**Issue by winup-zhou** [pop4959/Bolt#149]
### Server Information:

- Java 21 (OpenJDK 64-Bit Server VM 21.0.4+7-Ubuntu-1ubuntu220.04) Host: Linux 5.4.0-190-generic (amd64)
- Paper version 1.20.6-148-ver/1.20.6@20f5165

### Problem Description:
We found that a hopper or hopper cart **locked by player "a"** can remove items from containers (e.g., chests, shulker box) **locked by player "b"**.
Unlocked hoppers or hopper carts do not have this problem.

### Steps to reproduce the problem:

1. Place a chest and have **player "b"** lock it.
2. Place an **unlocked hopper** under the chest and notice that the item **is not removed from** the container.
3. Have **player "a" lock the hopper** you just placed.
4. The items in the container **appear in the hopper**, and the items in the container are **correspondingly reduced or disappeared**.

**Comment by pop4959** [comment]
I suspect this is caused by a misconfiguration (such as disabling the hopper move event) or plugin conflict rather than Bolt. Please join the [Discord server](https://discord.gg/ZwVJukcNQG) for help troubleshooting and if this is actually a bug, we'll re-open this issue.

**Comment by winup-zhou** [comment]
Thank you very much for your reply, we are currently speculating that this may not be a bug, but rather a corrupted bolt plugin file in our server causing the issue.   
This is because we have reproduced inconsistent behavior on another server with the same configuration.
