### ISSUE TITLE
Request - Drop Transfer

### ISSUE THREAD

**Issue by StarfireHunter** [pop4959/Bolt#150]
This is how it works on LWC. I would love to see it in Bolt.

> Drop transfer
> Permission: lwc.mode.droptransfer
> 
> Drop transfer allows you to do just that: drop transfer items to your chest. It does not work across world boundaries and will only transfer to a chest in the current world. There is currently no limit to the range.
> 
> When you drop an item (or stack) from your inventory to the ground, it will be transferred to the chest. If the chest is full, you will be notified and the items that did not fit will be returned to you.
> 
> To enable it first you need to select a chest using /cdroptransfer select to mark it as your target.
> 
> Once you select it, drop transferring is ON until you either disable it with /cdroptransfer off or log out.
> 
> Logging out will clear your drop transfer target. Using /cdroptransfer off will temporarily disable it -- you can re-enable it with /cdroptransfer on without reselecting your chest.
> 
> Finally, you can view the current status of drop transfer with /cdroptransfer status

**Comment by pop4959** [comment]
I don't currently have any plans or desire to maintain this kind of feature as part of Bolt. There are very few people interested in this feature (in fact, you're probably the first to ask in the last 2 years!) and it's not really relevant functionality for a protection plugin to include.

That isn't to say it isn't possible to have this feature alongside Bolt, e.g. via a Bolt add-on plugin. I would recommend looking into this yourself if you are interested.

The same is being done for other plugin integrations as well (for example, WorldGuard, ChestShop, Factions, Towny, are all separate plugins and not built straight into Bolt).

I hope this makes sense! Let me know if you have any other questions or concerns.
