### ISSUE TITLE
Autoclose not working 

### ISSUE THREAD

**Issue by jarda09** [pop4959/Bolt#156]
I have the latest version of Bolt 1.1.26
Server version: Paper version 1.21.3-46-master@f8e2a67

Autoclose works only for doors; fence_gates and trapdoors not working.

**Comment by pop4959** [comment]
I think this is closely related to #155, I just have not had a chance to look at this and make another release. Can you test and see if this was an issue prior to 0b9b9b92c3ed4854a137dee52dade8db5ae80ccc?

**Comment by pop4959** [comment]
Fixed
