### ISSUE TITLE
Support for new boat entities on 1.21.3+

### ISSUE THREAD

**Issue by takatalvi** [pop4959/Bolt#158]
Hello, somewhere between 1.21.1 and 1.21.3, boat and chest boat entities got split into separate entity IDs, based on wood type. I'm opening this issue for Bolt because its default config doesn't yet account for these new IDs. If there are group IDs like `#boats` or `#chest_boats`, that would be the best option. If not, here's a list of all the entity IDs:

```
oak_boat
spruce_boat
birch_chest_boat
dark_oak_boat
jungle_boat
cherry_boat
acacia_boat
mangrove_boat
bamboo_raft

oak_chest_boat
spruce_chest_boat
birch_chest_chest_boat
dark_oak_chest_boat
jungle_chest_boat
cherry_chest_boat
acacia_chest_boat
mangrove_chest_boat
bamboo_chest_raft
```

**Comment by pop4959** [comment]
Fixed + added pale oak as well as that was missing from the list.

Only boats with containers mounted on them are locked in the default config for Bolt however, you will need to add the rest yourself if you want all boats locked.

Unfortunately, as discovered, there are no vanilla tags for these so they have to be added individually (oh well).
