### ISSUE TITLE
Have /cnolock continue between player sessions

### ISSUE THREAD

**Issue by livelaughlemon** [pop4959/Bolt#3]
I've heard a lot from server players is that there should be an option to always have something like /cnolock enabled, so people can have it kept off until they turn it back on, which is important for a lot of things with slimefun and other plugins. Much appreciated, and ty for all the quick responses on spigot and discord :)

**Comment by pop4959** [comment]
Probably won't get to this right away but persistent player settings is something that I do want to add

**Comment by pop4959** [comment]
Partially done - not persistent between sessions yet but I've added a no lock mode

**Comment by pop4959** [comment]
This is now done @livelaughlemon. Please let me know if you have any more feedback!
