### ISSUE TITLE
Locks are getting removed in creative mode even when the block stays in place

### ISSUE THREAD

**Issue by takatalvi** [pop4959/Bolt#39]
in creative mode, whenever you left-click on a locked block with a tool which doesn't break the block instantly (e.g. hit a chest with a sword), the lock is removed.  the same thing can be observed when working with a debug stick. it looks like bolt expects the block to be broken instantly, so it removes the lock even when the block is not broken
- this happens only in creative mode
- you have to have "destroy" permission on the lock, (either owner or admin) so it's not a security issue
- if you left-click a block with an empty hand, with a solid block or certain tools (e.g. pickaxe), the block is destroyed instantly, which also removes the lock. this is correct behavior
- if you use a tool which doesn't destroy the block (e.g. sword), the lock is removed anyway. in this case, bolt should check if the block is destroyed or not, before removing the lock

**Comment by pop4959** [comment]
Fixed by ce87a1f70513f128cc95fba4e62f8b43aa146095
