### ISSUE TITLE
Suggestion: Cancel pending Bolt actions on more occasions

### ISSUE THREAD

**Issue by takatalvi** [pop4959/Bolt#41]
hi, i've noticed that when you have a pending action on Bolt (after typing a protection command), the action is pending until you click on a protectable block, either with a success or with an error. but without that, it's not possible to cancel the action. it might be a bit more user-friendly if the action was cancelled even when clicking on a non-protectable block, with a message "This block cannot be protected", or something along those lines. another option would be a command like /bolt cancel, to cancel the pending action, but i believe the former is a bit more better for the user experience. thanks!

**Comment by pop4959** [comment]
Added in 5ec22376fc1462b060df772580b432504cd32413
