### ISSUE TITLE
Feature request: Add protection to already placed objects

### ISSUE THREAD

**Issue by SlimeDog** [pop4959/Bolt#54]
We would like to add Bolt protection to objects that already exist in the world. We have not previously used a protection plugin.

Is there a clickable way to do that, without re-placing them?

**Comment by pop4959** [comment]
Yes there are a couple ways you could handle this:

First method would be something like `/lock` and `/bolt persist` to enable persist mode. Persist lets you repeat the same actions multiple times, so you'd just go around and click everything that you want to lock.

Second method is pick something up like the [Bolt WorldGuard addon](https://github.com/pop4959/BoltWorldGuard) and use regions with `/protectregion <region>` to automatically protect anything in an area that can be protected to yourself.

If neither of those seems suitable and there's another method you would want to see in Bolt let me know!

**Comment by SlimeDog** [comment]
One of those should do the trick. Thanks for the quick and informative response.

**Comment by pop4959** [comment]
Absolutely, glad to hear those work for you :)

There is more information on the [wiki](https://github.com/pop4959/Bolt/wiki) if you are interested about details, and if you have any other questions feel free to let me know.

**Comment by SlimeDog** [comment]
Thanks. I had read the wiki, but wasn't able to put 2+2 together. Your comments above make it clear.

**Comment by pop4959** [comment]
The wiki is a work in progress. I'll take a look later and see if I can make things more clear there, thanks for the feedback.
