### ISSUE TITLE
No confirmation when modifying trust access type

### ISSUE THREAD

**Issue by BornToDoStuff** [pop4959/Bolt#63]
When I type `/bolt modify add player admin TestSubject ` I would expect it to then ask something about "please type '/bolt trust confirm' to make these changes" or similar, but it does not, which makes it very unclear for the user what the next step is.

**Comment by pop4959** [comment]
Planning to revisit these as I still don't think the trust commands quite live up to expectations in terms of being user friendly, beyond the shortcuts that got added for basic access.

**Comment by pop4959** [comment]
Closing this one since changes for #64 should address this already when I get around to that. It's pointless to make any further changes here if we move to a system that doesn't use a confirmation.
