### ISSUE TITLE
Modifying player's trust-level access is unintuitive

### ISSUE THREAD

**Issue by BornToDoStuff** [pop4959/Bolt#64]
Currently to modify a player's trust access the command would look something like `/bolt modify add player admin TestSubject`. Intuitively this makes me think it is modifying the players global access level, not their trust access level.

I think that both for ease (less commands needed) and clarity (it makes it obvious what context it is) the command should look something like `/bolt trust add TestSubject <access>` where the optional access parameter determines if the user has a non-standard access to your protections, rather than needing to be added to your trust, and then modified with an unintuitive command.

**Comment by pop4959** [comment]
Mentioned this in the previous issue but this definitely needs some work, ideally just removing the extra commands I think. It shouldn't be as confusing as it is right now.

**Comment by pop4959** [comment]
Another issue to look into to make things more intuitive: sources that do not require an identifier should not require an identifier to be specified.

Example: `/bolt modify add autoclose door door` should be `/bolt modify add autoclose door` since door is inherent to the door itself.

**Comment by pop4959** [comment]
Updated in the latest version. The format is now `/bolt trust (add|remove) <sourcetype> <sourceidentifier> [accesstype]` (so required "player" and "name", but access can be optional and defaults to the default access type).

Also addressed the last comment which is that you don't need to redundantly identify a source type that is already implied.

So the door command would become `/bolt modify add autoclose door` which is more intuitive.
