### ISSUE TITLE
Add more information to the /bolt info command

### ISSUE THREAD

**Issue by BornToDoStuff** [pop4959/Bolt#65]
It would be really great to have a verbose information mode. Possibly even like `/bolt info verbose` which lets you see more information about the protection type. What nodes are enabled for the protection type, and when the protection was created would be the minimum, but something like who is on the owner's trust list, and when the protection was last accessed could be really nice as well.

**Comment by pop4959** [comment]
I believe there is a perm already for this (at least, for the access list, both the owner and anyone with the full access list perm get to see more information). What kind of information would you want to see about the protection?

**Comment by BornToDoStuff** [comment]
What nodes are enabled for the protection type by default (open, redstone, etc), and when the protection was created would be the minimum, but things like who is on the protection owner's trust list, and when the protection was last accessed could be really nice as well.

**Comment by pop4959** [comment]
Maybe not very obvious but `bolt.command.info.full` does actually display the access list. Only basic information is shown by default since players are able to access this command normally.

**Comment by rymiel** [comment]
Here is what `/bolt info` now looks like with the `bolt.command.info.full` permission (or if you're the owner of the claim)
![image](https://github.com/pop4959/Bolt/assets/53803019/9f4be683-89e3-4644-9233-dfe1da196938)
You can also see the exact timestamp with a hover
![screenshot_20240209_100340](https://github.com/pop4959/Bolt/assets/53803019/83e78a4f-24fe-4360-ab33-29573e22377a)
