### ISSUE TITLE
Allow /bolt lock <protection> to modify ALL existing protections

### ISSUE THREAD

**Issue by BornToDoStuff** [pop4959/Bolt#66]
This was an issue that would often happen in LWC, and is still a bit of an annoyance in Bolt, where there is an existing protection and as an admin you want want to change it... in some cases you first must entirely unlock that protection and then in some cases also re-add all the settings it had (transfer it to the old owner, etc). I believe this occurs when you dont own the protection, regardless of your ability to remove or edit it. It doesnt seem like this should really be necessary. If I have edit and destroy permissions to the protection, why cant I change the protection type just because I dont own it?

**Comment by pop4959** [comment]
This seems like an oversight, thanks for pointing that out. Should be possible (at the very least, with a `/bolt admin lock` version like is done with other basic commands to override any permissions set on a protection).

**Comment by pop4959** [comment]
From Discord discussion: maybe include this under the `edit` permission (admins would have access to this anyways, and it can be set for players).

**Comment by pop4959** [comment]
Edit permission will now work in place of strictly owner as of 25e8495113a74f20798c4958c5fbdfb1bf78415e
