### ISSUE TITLE
Unable to push locked Minecart Hoppers into blocks using a piston

### ISSUE THREAD

**Issue by vinibailo** [pop4959/Bolt#67]
Hi there,

I'm currently using your container lock/protection plugin on my Minecraft server and I've stumbled upon an issue related to locked Minecart Hoppers. Specifically, if a Minecart Hopper is locked, it seems to become immovable by a piston.

**Steps to reproduce:**

1. Place a Minecart with Hopper and lock it using the plugin's lock command.
2. Try to push the locked Minecart Hopper into a block using a piston.

**Expected result:**
The piston should be able to push the locked Minecart Hopper into a block, similar to how it would behave if the Minecart Hopper were not locked or in Vanilla Minecraft

**Actual result:**
The piston fails to push the locked Minecart Hopper.

This seems to be a bug because locked or not, a Minecart Hopper should still be able to be moved by a piston. This issue impacts gameplay because it prevents the creation of certain contraptions and mechanisms that rely on the ability to move Minecart Hoppers into blocks, like farms.

I'm looking forward to your thoughts on this. Please let me know if there is any additional information that I could provide.

**Comment by pop4959** [comment]
It's actually not a bug, it's intended to prevent other players from messing with your protections using pistons and so on, but it seems like it backfires in a way since the owner also can't do that. This is an oversight, so I'll probably add a permission or something of the sort to allow this.

**Comment by pop4959** [comment]
Discussed on Discord - decided ultimately for now it makes far more sense to just remove these entity checks than add extra complexity here. Keep in mind that this is not a firm stance - might re-add in the future if it makes sense, but at the moment I can't really think of any reasons why it would be particularly helpful (besides potentially preventing minor trolling).
