### ISSUE TITLE
Restrict protected sculk sensors

### ISSUE THREAD

**Issue by MC-MrBirdy** [pop4959/Bolt#68]
When protecting a sculk sensor to only allow players/entities with access to trigger it.
(Same could apply for the calibrated version).

Currently it is possible to allow sculk sensors to be protected, but they still allow anything (that is possible) to trigger them.

**Comment by pop4959** [comment]
Okay so looking into this, it looks like this is controlled by redstone events. So, if you disable redstone permissions on the sculk sensors it will not be possible to activate them. Unfortunately it's not possible currently to restrict redstone actions to certain players.

**Comment by pop4959** [comment]
Nevermind, seems like redstone interaction is different from the sculk activation. This should work now for players.
