### ISSUE TITLE
Locked armor stand cannot move via slime/honey blocks

### ISSUE THREAD

**Issue by c0wg0d** [pop4959/Bolt#74]
Bolt 1.0.503
Paper version git-Paper-62 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 4356758)

If you place a sticky piston horizontally with a honey block in front, then place an armor stand on top of the honey block and activate the piston with a lever, the piston will not activate.  If you /unlock the armor stand, it will activate normally.

If you make a slime block launcher that shoots an armor stand in the air, it behaves the same way when the armor stand is locked.  Here is an example of the slime block launcher: https://youtu.be/oDzmzojNpO8?t=42

I thought perhaps just "redstone" wasn't enough and it needed "interact", so I tried /bolt lock display, but the result is the same.

**Comment by pop4959** [comment]
Technically this was "correct" behavior based on how the matcher for armor stands was made to work, but it seems a bit unnecessary in hindsight, as there is nothing that needs to be matched here. It just breaks contraptions as you've pointed out. I've gone ahead and removed this behavior in a0fa8402914dbb890b3e5067e729feb170120f1c. If there is ever a need for it to return, for any reason, it will have configuration associated with it (but for the time being, not sure this even needs to be a thing).
