### ISSUE TITLE
Bolt Commands, when blocked via worldguard cmd-block flag, can be bypassed

### ISSUE THREAD

**Issue by ClickErrorxD** [pop4959/Bolt#76]
I have been trying to block `/lock` and `/bolt lock` in our spawn. However, when I tried to take the easiest route possible, which was using worldguard's block-cmd flag to block these two commands, it works up until player's leave the region it's blocked in, going to another region where it's unblocked, such as your survival world, typing `lock`, it then tells the player to click a container. If a player just goes to spawn, or wherever you've blocked those commands, they can still click the chest to lock it.

I would say the bug is that this process (the clicking of container) should be cancelled upon worldchange or any teleportation method.
I'm not sure if this is a bug or suggestion, I was told to note this over on discord. [Discussion found here.](https://discord.com/channels/390942438061113344/479919881702342676/1133113467688194218)

**Comment by pop4959** [comment]
Should see if we can check the permissions when the interaction occurs in addition to when the command is run

**Comment by pop4959** [comment]
Added in 805df082939812e05654095642d3f65347133479. Keep in mind that your `blocked-cmd` option may still not work for this, as what it'll do is check the permission on use. If you want to disable the command and usage in the specific region, you will want to use a permission context instead. For WorldGuard this can quite easily be done with [ExtraContexts](https://github.com/LuckPerms/ExtraContexts), enabling the `worldguard:region` context, and using that.
