### ISSUE TITLE
Inconsistent behavior with locks and entities

### ISSUE THREAD

**Issue by Lorias-Jak** [pop4959/Bolt#77]
When `/lock display` is made, you can put items in from itemframes, but not take them out. With armorstands you can put items up and take them down.

With `/lock deposit` you can put Armor on Armorstands and take it off, with the Itemframe neither the putting in nor the taking out works.

**Comment by pop4959** [comment]
Should look into what events there are for checking this, since it isn't a standard inventory / container transaction

**Comment by pop4959** [comment]
Item frames added with #82 in 74e42c5c8f925b0101fdaed91a9331aa22852227, armor stands in 76149d05cb0b7fa26580e9cb802f1a04d499b30d. Two sides of the same coin, just had to make sure to handle these specially since they aren't actually inventories as previously mentioned.
