### ISSUE TITLE
Locked doubledoor interaction with trapdoor and door

### ISSUE THREAD

**Issue by Lorias-Jak** [pop4959/Bolt#78]
https://cdn.discordapp.com/attachments/771787182494974012/1135311824397545553/Base_Profile_2023.07.30_-_22.43.01.08.DVR.mp4

<img width="686" alt="image" src="https://github.com/pop4959/Bolt/assets/62625225/f46d8be0-39ff-430a-b3f2-a19c1604f2a0">

**Comment by Lorias-Jak** [comment]
In addition to say, it only happens if i open the door, not the trapdoor

**Comment by pop4959** [comment]
Interesting, I will see if this can be improved - ideally only matching doors should be openable in pairs

**Comment by pop4959** [comment]
Fixed with 7497ead84a79a6d4f319b77e51663a956252bca6.
