### ISSUE TITLE
Canceled Sign Interactions

### ISSUE THREAD

**Issue by Lorias-Jak** [pop4959/Bolt#79]
It turns out that sign actions belonging to the PlayerInteractEvent are canceled when they are locked. Through a little debugging I was able to figure out that the PlayerInteractEvent is called twice on bolt. The first time it runs through a bit, the second time it cancels as soon as boltPlayer#hasInteracted is called, there the event is canceled. Its confusing that the event is called twice within one interaction, maybe you know why this happens?

I use the plugin CraftBook and the [Gate] function. As soon as the sign is locked by anyone, you can't use it at all. Also not the person who locked it.

Paper 1.20.1 - 100
Bolt 1.0.503

https://github.com/pop4959/Bolt/assets/62625225/8eca4b02-b430-4bc1-8ef5-7db4c457ef98

**Comment by pop4959** [comment]
Will definitely look into this soon. Thanks for the report!

**Comment by pop4959** [comment]
Added some more careful handling around cancellation of the event, looks to work now.

I have tested a fair bit, but I advise caution since the patch strictly cancels less than it used to, so hopefully there aren't any unintended side effects of that.
