### ISSUE TITLE
Add "/lwc admin expire" command compatibility

### ISSUE THREAD

**Issue by GLufano** [pop4959/Bolt#80]
In LWC it was possible to remove inactive protections with the command ``/lwc admin expire <time>``, even with some problems in removing protections from active people, it was an efficient way to remove protections that had been unused for a long time on a large scale.

It would be interesting to add it to Bolt as it would be an extra tool for the administration to clear protections.

**Comment by pop4959** [comment]
Agree, this was an oversight but will look at adding this soon.

**Comment by pop4959** [comment]
Added in fb1bc1934750dd74cf876b7c22405c9495922392.
