### ISSUE TITLE
Support deposit/withdrawal permission on Item Frames

### ISSUE THREAD

**Issue by takatalvi** [pop4959/Bolt#82]
Hi, one of my players and I have found an issue with item frames - when locked as public (allowing both deposit and withdrawal, as per config), the withdrawal doesn't work. Other players can rotate the item in the frame, can put an item in an empty public frame, but can't take the item out of it. I've checked armor stands and they are working correcly. It seems that only item frames (including glowing ones) don't allow withdrawal even if it's allowed in the protection type.

Thanks!

**Comment by pop4959** [comment]
Added in 74e42c5c8f925b0101fdaed91a9331aa22852227.
