### ISSUE TITLE
[feature] shortcuts for /bolt modify

### ISSUE THREAD

**Issue by liki-mc** [pop4959/Bolt#83]
Request to add shorter commands for
- /bolt modify add normal group <group-name>
- /bolt modify add normal player <player-name>

a possible shorter command could be
- /bolt gmodify <group-name>
- /bolt pmodify <player-name>

**Comment by pop4959** [comment]
There is no interest in adding these hard-coded shortcuts, especially considering that all of the protection and access types can be renamed to anything (so effectively it's useless even trying to start trying to do that).

In your situation, I would advise creating aliases through `commands.yml` on the server if you have specific shortcuts in mind.
