### ISSUE TITLE
Action bar messages not working on 1.20.2

### ISSUE THREAD

**Issue by takatalvi** [pop4959/Bolt#89]
Hi, this was brought up by another user on Discord but I thought I'd post it here so it's not lost.

Since updating Paper to 1.20.2, Bolt doesn't show any action bar messages it's supposed to, even when settings.use-action-bar is set to true.
Example: you enter /bolt info, which should display "Click on a protection to view info." but it doesn't. The command works though - after clicking, the protection info is displayed. It just seems that the action bar messages get stuck at some point.

**Comment by pop4959** [comment]
Fixed in fd9c50ee583c8d5b0e9f6843577a1ece4343a23d
