### ISSUE TITLE
Players can lock blocks in WorldGuard regions of others

### ISSUE THREAD

**Issue by arskvsh** [pop4959/Bolt#90]
Bolt 1.0.515, WorldGuard 7.0.10, Paper 1.20.1 Build 196

Players can lock blocks in the regions that they are neither owners nor members of, resulting in that nobody except admins can use these blocks. The only way to avoid this for a region owner is to preventively lock everything that can be locked.
It would be nice to have an integration with WorldGuard to check if the player is an owner or a member in a region before allowing to create Bolt protection there. If I am not mistaken, LWC was able to do that.

**Comment by pop4959** [comment]
Latest version of BoltWorldGuard has this feature, you will need to download the latest dev builds of both through CodeMC or Actions until there is a proper release though.
