### ISSUE TITLE
Allowing several players to modify /bolt groups and existing protections.

### ISSUE THREAD

**Issue by SoulReapingWolf** [pop4959/Bolt#91]
Hey there! /bolt groups is a super useful feature and have made a bunch of organizing and giving out access to people in the different player bases. I wanted to ask a couple of things if it's in the plans for the future to add something similar to what /lwc had where you could give admin permissions to particular protections (think it was /cmodify @player) or to modify an existing /bolt group?

This is particularly useful in different scenarios like in a faction giving out this access or the ability to modify these permissions to a second in command or two, that way if you are offline then you don't need to worry about new members of your faction being unable to get access to the Faction's storage.

**Comment by pop4959** [comment]
Yes, it is already supported actually. The access levels are in the config, default is "normal" and "admin" access. You can set up as many different access levels as you want which can be changed with [`/bolt modify`](https://github.com/pop4959/Bolt/wiki#modify) currently (somewhat similar to `/cmodify`, see the wiki for more details).

You may also be interested in setting up the [BoltFactions](https://modrinth.com/plugin/boltfactions) addon which lets you add factions directly to protections via the faction access type.

Let me know if you have any other questions or join the [Discord server](https://discord.gg/PHpuzZS).
