### ISSUE TITLE
Add the ability to configure mode defaults

### ISSUE THREAD

**Issue by MissPotato** [pop4959/Bolt#97]
Currently, the defaults are great for most users. However, if we were able to set the default mode, this would allow auto-claims to be opt-in. 

Most of the players on my serve rwant claims to be a per-chest basis. While this can be done by setting auto-protect to false for all protected blocks, this means that anyone who wants everything to be claimed will have to do `/bolt mode persist` `/lock private` right click everything they placed, and do `/bolt mode persist` again. 

If `/bolt mode nolock` was changed to default to true, players could change it back off and it would go back to auto-claiming everything.

**Comment by pop4959** [comment]
In the latest version you can now add default modes to the config.

For example:
```yml
settings:
  default-modes:
    - nolock
```
