### ISSUE TITLE
Allow mods open locked containers

### ISSUE THREAD

**Issue by broken1arrow** [pop4959/Bolt#98]
I almost forget to make a issue about it. 

As the title stated, as it is now mods can only unlock, but not open others locked containers. At least on my server shall mods have access to most of the plugin beside reload and convert data and similar more sensitive commands (that should be either under admin or separated permission).

**Comment by pop4959** [comment]
Updated permission checks in 6f2cf1f8d78aafa4817a6c2fe25a268f20f6b780 and fa6860bbd5c9f1ec56c9ccc2a43752c36c3412b4.

You can now add specific global protection permissions via the `bolt.permission.<permission>` permission.

In addition, `bolt.mod` has been changed to be less destructive, allowing the usual "display" set of permissions.
For editing/destroying protections, the `bolt.admin` permission still exists which does that (and does not give access to admin commands or anything like that, as that is under the separate `bolt.command.admin` permission and subpermissions).
