### ISSUE TITLE
Uses event deprecated for removal

### ISSUE THREAD

**Issue by rymiel** [pop4959/Bolt#99]
`org.spigotmc.event.entity.EntityMountEvent` is deprecated for removal and is replaced by `org.bukkit.event.entity.EntityMountEvent`

https://github.com/pop4959/Bolt/blob/c305c078cfe68aaa67b89397340426e86f7cf5bc/bukkit/src/main/java/org/popcraft/bolt/listeners/EntityListener.java#L590

**Comment by pop4959** [comment]
The replaced event only exists in 1.20, so we will need to wait a little bit before replacing it in Bolt (since we support the current and last released Minecraft version, right now 1.19 and 1.20).

**Comment by pop4959** [comment]
Okay this was actually just replaced in 1.20.4, so it will be a while before I can actually remove it from the code. For now just adding a comment to remind myself to remove it and suppressing the deprecation notice so it's not a bother in IDEA. Probably removing in 1.22 or so as per the general policy around backwards compatibility I mentioned above.
